"""
VibeMatch AI - end-to-end demo.

Shows the full applied-AI workflow for three listener profiles plus one
deliberately-invalid profile that exercises the guardrails:

    input -> guardrails -> rule-based recommender -> retrieval -> AI explanation

Run from the project root:

    python run_demo.py

By default the AI explanation layer runs offline (deterministic fallback). If
you set ANTHROPIC_API_KEY (and have the ``anthropic`` package installed), the
explanations are generated by Claude instead - the rest of the demo is
identical either way.
"""

import os

from src.pipeline import run_profile

# Three well-formed profiles plus one messy profile to show validation.
DEMO_PROFILES = [
    {
        "name": "Pop Party",
        "prefs": {
            "genre": "pop",
            "mood": "happy",
            "energy": 0.85,
            "target_tempo": 124,
            "likes_acoustic": False,
        },
    },
    {
        "name": "Lofi Study Session",
        "prefs": {
            "genre": "lofi",
            "mood": "focused",
            "energy": 0.40,
            "target_tempo": 78,
            "likes_acoustic": True,
        },
    },
    {
        "name": "Rock Workout",
        "prefs": {
            "genre": "rock",
            "mood": "intense",
            "energy": 0.92,
            "target_tempo": 148,
            "likes_acoustic": False,
        },
    },
    {
        # Intentionally broken: unknown mood, non-numeric energy, negative tempo.
        "name": "Messy Input (guardrail demo)",
        "prefs": {
            "genre": "POP",
            "mood": "party-vibes",
            "energy": "loud",
            "target_tempo": -20,
            "likes_acoustic": "yes",
        },
    },
]


def _print_profile(profile: dict) -> None:
    name = profile["name"]
    print("=" * 70)
    print(f"User profile: {name}")
    print(f"  raw input: {profile['prefs']}")
    print("-" * 70)

    result = run_profile(profile["prefs"], k=3)

    if result["warnings"]:
        print("Guardrails adjusted the input:")
        for warning in result["warnings"]:
            print(f"  ! {warning}")
        print(f"  -> using: {result['clean_prefs']}")
        print("-" * 70)

    for rank, rec in enumerate(result["recommendations"], start=1):
        song = rec["song"]
        exp = rec["explanation"]
        print(f"{rank}. {song['title']} - {song['artist']} (score: {rec['score']:.2f})")
        print(f"   Summary:  {exp['summary']}")
        print(f"   Why:      {exp['why_it_fits']}")
        context_oneline = " ".join(exp["genre_mood_context"].split())
        print(f"   Context:  {context_oneline}")
        print(f"   Caveat:   {exp['caveat']}")
    print()


def main() -> None:
    backend = "Claude API" if os.environ.get("ANTHROPIC_API_KEY") else "offline fallback"
    print(f"VibeMatch AI demo - explanation backend: {backend}\n")
    for profile in DEMO_PROFILES:
        _print_profile(profile)


if __name__ == "__main__":
    main()
